---
- name: Install nginx
  yum:
   name: nginx
   state: present

- name: Create Config for nginx
  template:
   src: nginx.j2
   dest: /etc/nginx/nginx.conf

- name: Make sure nginx is started
  systemd:
    name: nginx
    state: started
    enabled: true
  register: result

- name: Show result
  debug:
    msg: "{{ result }}"


  
     
