---
- name: Install nginx
  yum:
   name: nginx
   state: present

- name: Create Config for nginx
  template:
   src: nginx.j2
   dest: /etc/nginx/nginx.conf
  notify:
   - reload nginx config

- name: Make sure nginx is started
  systemd:
    name: nginx
    state: started
    enabled: true
    
